name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Setup term
        run: echo "TERM=linux" >> $GITHUB_ENV
      - name: Run tests
        run: python -m unittest